### ISSUE TITLE
Check goal fails if the same dependency is inculded twice

### ISSUE THREAD

**Issue by jakub-bochenski** [basepom/duplicate-finder-maven-plugin#10]
I'm getting the following error, my guess is that because the project includes both 

		<dependency>
			<groupId>com.acme.filestore</groupId>
			<artifactId>common</artifactId>
			<version>${project.version}</version>
		</dependency>

and

		<dependency>
			<groupId>com.acme.filestore</groupId>
			<artifactId>common</artifactId>
			<version>${project.version}</version>
			<classifier>tests</classifier>
			<scope>test</scope>
		</dependency>
and

				<dependency>
					<groupId>com.acme.filestore</groupId>
					<artifactId>common</artifactId>
					<version>${project.version}</version>
					<classifier>tomcat</classifier>
					<type>tgz</type>
				</dependency>

```maven
[ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.1.1:check (default) on project psmgr: Execution default of goal org.basepom.maven:duplicate-finder-maven-plugin:1.1.1:check failed: value already present: /home/acme/gotham/trunk/java/common/target/classes -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.1.1:check (default) on project psmgr: Execution default of goal org.basepom.maven:duplicate-finder-maven-plugin:1.1.1:check failed: value already present: /home/acme/gotham/trunk/java/common/target/classes
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.basepom.maven:duplicate-finder-maven-plugin:1.1.1:check failed: value already present: /home/acme/gotham/trunk/java/common/target/classes
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.IllegalArgumentException: value already present: /home/acme/gotham/trunk/java/common/target/classes
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
        at org.basepom.mojo.duplicatefinder.artifact.ArtifactFileResolver.<init>(ArtifactFileResolver.java:102)
        at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.execute(DuplicateFinderMojo.java:339)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        ... 20 more
```

**Comment by hgschmie** [comment]
Thanks for reporting this, will look into it.

**Comment by hgschmie** [comment]
Fix is in https://github.com/basepom/duplicate-finder-maven-plugin/pull/15
