### ISSUE TITLE
Check goal fails if same dependency included twice without packaging jars

### ISSUE THREAD

**Issue by seanf** [basepom/duplicate-finder-maven-plugin#25]
I get a similar error message to #10, but I am running version 1.2.1, and the error only happens when compiling modules, not when packaging them as jars.

* p1 generates a default jar and a sources jar
* p2 has both p1 and p1:sources as a dependency.

Invoke this way:

    mvn clean compile org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check

Error:

	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check (default-cli) on project test-issue-99-p2: Execution default-cli of goal org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check failed: value already present: /home/sflaniga/NotBackedUp/src/duplicate-finder-maven-plugin/src/it/test-issue-99/p1/target/classes
	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	        at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:334)
	        at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:104)
	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	        at java.lang.Thread.run(Thread.java:745)
	Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check failed: value already present: /home/sflaniga/NotBackedUp/src/duplicate-finder-maven-plugin/src/it/test-issue-99/p1/target/classes
	        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	        ... 10 more
	Caused by: java.lang.IllegalArgumentException: value already present: /home/sflaniga/NotBackedUp/src/duplicate-finder-maven-plugin/src/it/test-issue-99/p1/target/classes
	        at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
	        at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	        at org.basepom.mojo.duplicatefinder.artifact.ArtifactFileResolver.<init>(ArtifactFileResolver.java:91)
	        at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.execute(DuplicateFinderMojo.java:362)
	        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	        ... 11 more

Similar errors can be seen with shaded jars.

I don't see the problem when using:

    mvn clean package org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check

Sample project:

[test-issue-99.zip](https://github.com/basepom/duplicate-finder-maven-plugin/files/568141/test-issue-99.zip)

**Comment by hgschmie** [comment]
Turns out, this is the same bug as #35. Will be fixed in the next release. Sorry, that it slipped through the cracks for me.
